quarkus:
  http:
    port: 8080
    cors:
      enabled: true
      origins: "*"
  smallrye-openapi:
    path: /openapi
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:file:./var/techwatch
      driver: org.h2.Driver
    username: sa
    password: ""
  hibernate-orm:
    log:
      sql: false  # Mettre à true si vous voulez voir les requêtes SQL

  liquibase:
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.yaml

"%dev":
  quarkus:
    hibernate-orm:
      log:
        sql: true

"%native":
  quarkus:
    native:
      enabled: true
      resources:
        includes: "META-INF/resources/**"
    package:
      jar:
        enabled: false
    http:
      static-resources:
        index-page: index.html
      auth:
        permission:
          public-static:
            policy: permit
            methods: GET,HEAD
            paths:
              - /
              - /index.html
              - /favicon.ico
              - /assets/*
              - /*.js
              - /*.css
              - /*.map
              - /*.png
              - /*.svg
              - /*.ico

"%prod":
  quarkus:
    http:
      static-resources:
        index-page: index.html
      auth:
        permission:
          public-static:
            policy: permit
            methods: GET,HEAD
            paths:
              - /
              - /index.html
              - /favicon.ico
              - /assets/*
              - /*.js
              - /*.css
              - /*.map
              - /*.png
              - /*.svg
              - /*.ico
